### ISSUE TITLE
Feature suggestion: correlation matrix

### ISSUE THREAD

**Issue by smjure** [viterin/vek#2]
Thank you for the package, the results are awesome.

Would it be possible to add correlation matrix? It's something that can be highly paralelized and vecotrized.

**Comment by viterin** [comment]
Sorry for the (very) late response, glad to hear it's useful! There are no plans to add matrix operations besides the basic `vek.MatMul`. The main goal of vek is to accelerate simple vector operations without the overhead or hassle of a CGO library, it's not a statistics or linear algebra library.

You can probably speed up correlation matrix computation using vek primitives, but I'd recommend just using [gonum](https://www.gonum.org/) which can do it out of the box.
