### ISSUE TITLE
Will not build in Go v1.21

### ISSUE THREAD

**Issue by delaneyj** [viterin/vek#4]
go1.21.0/global/pkg/mod/github.com/viterin/partial@v1.0.0/sort.go:26:28: type func(E, E) bool of less does not match inferred type func(a E, b E) int for func(a E, b E) int (exit status 1)

**Comment by delaneyj** [comment]
Sorry realized its in the supporting library

https://github.com/viterin/partial/issues/2

**Comment by viterin** [comment]
Fixed in v0.4.2, thanks again for the report
